// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGbyDL3R6gFDeo8e7Yi3rfpSSUG2k7lQk',
    appId: '1:970438886543:web:8e9513759faa291935dcfa',
    messagingSenderId: '970438886543',
    projectId: 'fir-first-app-267fa',
    authDomain: 'fir-first-app-267fa.firebaseapp.com',
    storageBucket: 'fir-first-app-267fa.appspot.com',
    measurementId: 'G-L0KHLTGN6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZHv1HBuRGh2K064f0J-SmTahmzFaHaQw',
    appId: '1:970438886543:android:4eafa0e3ff4ab68635dcfa',
    messagingSenderId: '970438886543',
    projectId: 'fir-first-app-267fa',
    storageBucket: 'fir-first-app-267fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM9WCyfMftHFvsgHElQVmhD1lVqmL7TjI',
    appId: '1:970438886543:ios:f8f95e5b0e40fde635dcfa',
    messagingSenderId: '970438886543',
    projectId: 'fir-first-app-267fa',
    storageBucket: 'fir-first-app-267fa.appspot.com',
    iosBundleId: 'com.example.firebaseApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM9WCyfMftHFvsgHElQVmhD1lVqmL7TjI',
    appId: '1:970438886543:ios:62425d033e1cf2be35dcfa',
    messagingSenderId: '970438886543',
    projectId: 'fir-first-app-267fa',
    storageBucket: 'fir-first-app-267fa.appspot.com',
    iosBundleId: 'com.example.firebaseApp1.RunnerTests',
  );
}
